#ifndef OBSPLUGINSTREAMDECK_GLOBAL_H
#define OBSPLUGINSTREAMDECK_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(OBSPLUGINSTREAMDECK_LIBRARY)
#define OBSPLUGINSTREAMDECKSHARED_EXPORT Q_DECL_EXPORT
#else
#define OBSPLUGINSTREAMDECKSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // OBSPLUGINSTREAMDECK_GLOBAL_H
