/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "n4.2.4-23-g4074090291"
#endif /* AVUTIL_FFVERSION_H */
