#include "../pls-net-url.hpp"
#define PRISM_PC "prism_pc"
// Dev
// API host please refer 

const QString PLS_TERM_OF_USE_URL_DEV;
const QString PLS_PRIVACY_URL_DEV;
const QString PLS_PC_HMAC_KEY_DEV;
const QString g_streamKeyPrismHelperEn_DEV;
const QString g_streamKeyPrismHelperKr_DEV;
const QString LIBRARY_POLICY_PC_ID_DEV;
const QString LIBRARY_SENSETIME_PC_ID_DEV;
// MQTT
const QString MQTT_SERVER_DEV;
const QString MQTT_SERVER_PW_DEV;
const QString MQTT_SERVER_WEB_DEV;
// Prism auth api
const QString PRISM_AUTH_API_BASE_DEV;
const QString PLS_FACEBOOK_LOGIN_URL_DEV;
const QString PLS_GOOGLE_LOGIN_URL_TOKEN_DEV;
const QString PLS_LINE_LOGIN_URL_DEV;
const QString PLS_NAVER_LOGIN_URL_DEV;
const QString PLS_TWITTER_LOGIN_URL_DEV;
const QString PLS_TWITCH_LOGIN_URL_DEV;
const QString PLS_WHALESPACE_LOGIN_URL_DEV;
const QString PLS_SNS_LOGIN_SIGNUP_URL_DEV;
const QString PLS_EMAIL_LOGIN_URL_DEV;
const QString PLS_EMAIL_SIGNUP_URL_DEV;
const QString PLS_EMAIL_FOGETTON_URL_DEV;
const QString PLS_CHANGE_PASSWORD_DEV;
const QString PLS_LOGOUT_URL_DEV;
const QString PLS_SIGNOUT_URL_DEV;
const QString PLS_TOKEN_SESSION_URL_DEV;
// rtmp
const QString PLS_RTMP_ADD_DEV;
const QString PLS_RTMP_MODIFY_DEV;
const QString PLS_RTMP_DELETE_DEV;
const QString PLS_RTMP_LIST_DEV;
// prism sidekick api
const QString PLS_Sidekick_API_GATEWAY_DEV;
const QString PLS_NOTICE_URL_DEV;
const QString CONTACT_SEND_EMAIL_URL_DEV;
// prism sync api
const QString PLS_SYNC_API_GATEWAY_DEV;
const QString PLS_CATEGORY_DEV;
const QString PLS_GPOP_CATEGORY_DEV;
const QString UPDATE_URL_DEV;
const QString LASTEST_UPDATE_URL_DEV;
// Twitch
const QString TWITCH_CLIENT_ID_DEV;
const QString TWITCH_REDIRECT_URI_DEV;
// Youtube
const QString YOUTUBE_CLIENT_ID_DEV;
const QString YOUTUBE_CLIENT_KEY_DEV;
const QString YOUTUBE_CLIENT_URL_DEV;
// gpop
const QString PLS_GPOP_DEV;
//NaverTv
const QString CHANNEL_NAVERTV_LOGIN_DEV;
const QString CHANNEL_NAVERTV_AUTHORIZE_DEV;
const QString CHANNEL_NAVERTV_TOKEN_DEV;
const QString CHANNEL_NAVERTV_AUTHORIZE_REDIRECT_DEV;
const QString CHANNEL_NAVERTV_GET_AUTH_DEV;
const QString CHANNEL_NAVERTV_COMMENT_OPTIONS_DEV;
const QString CHANNEL_NAVERTV_UPLOAD_IMAGE_DEV;
//Vlive
const QString CHANNEL_VLIVE_LOGIN_DEV;
const QString CHANNEL_VLIVE_LOGIN_JUMP_DEV;
const QString CHANNEL_VLIVE_LOGIN_JUMP_1_DEV;
const QString CHANNEL_VLIVE_SHARE_DEV;
//Band
const QString CHANNEL_BAND_LOGIN_DEV;
const QString CHANNEL_BAND_ID_DEV;
const QString CHANNEL_BAND_REDIRECTURL_DEV;
const QString CHANNEL_BAND_SECRET_DEV;
const QString CHANNEL_BAND_AUTH_DEV;
const QString CHANNEL_BAND_REFRESH_TOKEN_DEV;
const QString CHANNEL_BAND_USER_PROFILE_DEV;
const QString CHANNEL_BAND_CATEGORY_DEV;
const QString CHANNEL_BAND_LIVE_CREATE_DEV;
const QString CHANNEL_BAND_LIVE_OFF_DEV;
//Facebook
const QString CHANNEL_FACEBOOK_CLIENT_ID_DEV; 
const QString CHANNEL_FACEBOOK_SECRET_DEV;
//Chat Widget
const QString CHAT_SOURCE_URL_DEV;
//Naver Shopping Live
const QString CHANNEL_NAVER_SHOPPING_LIVE_LOGIN_DEV;
const QString CHANNEL_NAVER_SHOPPING_LIVE_SMART_STORE_LOGIN_DEV;
//=============================================================================================================
//=============================================================================================================
// Real

QString PLS_TERM_OF_USE_URL;
QString PLS_PRIVACY_URL;
QString PLS_PC_HMAC_KEY;
QString PLS_VLIVE_HMAC_KEY;
QString g_streamKeyPrismHelperEn;
QString g_streamKeyPrismHelperKr;
QString LIBRARY_POLICY_PC_ID;
QString LIBRARY_SENSETIME_PC_ID;
// MQTT
QString MQTT_SERVER;
QString MQTT_SERVER_PW;
QString MQTT_SERVER_WEB;
// Prism auth api
QString PRISM_AUTH_API_BASE;
QString PLS_FACEBOOK_LOGIN_URL;
QString PLS_GOOGLE_LOGIN_URL_TOKEN;
QString PLS_LINE_LOGIN_URL;
QString PLS_NAVER_LOGIN_URL;
QString PLS_TWITTER_LOGIN_URL;
QString PLS_TWITCH_LOGIN_URL;
QString PLS_WHALESPACE_LOGIN_URL;
QString PLS_SNS_LOGIN_SIGNUP_URL;
QString PLS_EMAIL_LOGIN_URL;
QString PLS_EMAIL_SIGNUP_URL;
QString PLS_EMAIL_FOGETTON_URL;
QString PLS_CHANGE_PASSWORD;
QString PLS_LOGOUT_URL;
QString PLS_SIGNOUT_URL;
QString PLS_TOKEN_SESSION_URL;
// rtmp
QString PLS_RTMP_ADD;
QString PLS_RTMP_MODIFY;
QString PLS_RTMP_DELETE;
QString PLS_RTMP_LIST;
// prism sidekick api
QString PLS_Sidekick_API_GATEWAY;
QString PLS_NOTICE_URL;
QString CONTACT_SEND_EMAIL_URL;
// prism sync api
QString PLS_SYNC_API_GATEWAY;
QString PLS_CATEGORY;
QString PLS_GPOP_CATEGORY;
QString UPDATE_URL;
QString LASTEST_UPDATE_URL;
// prism action log
QString PRISM_API_ACTION;
// prism status log
QString PRISM_API_STATUS;
// prism api
QString PRISM_API_BASE;
// Twitch
QString TWITCH_CLIENT_ID;
QString TWITCH_REDIRECT_URI;
// Youtube
QString YOUTUBE_CLIENT_ID;
QString YOUTUBE_CLIENT_KEY;
QString YOUTUBE_CLIENT_URL;
// gpop
QString PLS_GPOP;
//NaverTV
QString CHANNEL_NAVERTV_LOGIN;
QString CHANNEL_NAVERTV_GET_USERINFO;
QString CHANNEL_NAVERTV_AUTHORIZE;
QString CHANNEL_NAVERTV_TOKEN;
QString CHANNEL_NAVERTV_AUTHORIZE_REDIRECT;
QString CHANNEL_NAVERTV_GET_AUTH;
QString CHANNEL_NAVERTV_COMMENT_OPTIONS;
QString CHANNEL_NAVERTV_UPLOAD_IMAGE;
QString CHANNEL_NAVERTV_DEFAULT_HEAD_IMAGE_URL;
QString CHANNEL_NAVERTV_GET_LIVES;
QString CHANNEL_NAVERTV_GET_STREAM_INFO;
QString CHANNEL_NAVERTV_QUICK_START;
QString CHANNEL_NAVERTV_OPEN;
QString CHANNEL_NAVERTV_CLOSE;
QString CHANNEL_NAVERTV_MODIFY;
QString CHANNEL_NAVERTV_STATUS;
//VLive
QString CHANNEL_VLIVE_LOGIN;
QString CHANNEL_VLIVE_LOGIN_JUMP;
QString CHANNEL_VLIVE_LOGIN_JUMP_1;
QString CHANNEL_VLIVE_SHARE;
//Band
QString CHANNEL_BAND_LOGIN;
QString CHANNEL_BAND_ID;
QString CHANNEL_BAND_REDIRECTURL;
QString CHANNEL_BAND_SECRET;
QString CHANNEL_BAND_AUTH;
QString CHANNEL_BAND_REFRESH_TOKEN;
QString CHANNEL_BAND_USER_PROFILE;
QString CHANNEL_BAND_CATEGORY;
QString CHANNEL_BAND_LIVE_CREATE;
QString CHANNEL_BAND_LIVE_OFF;
//Facebook
QString CHANNEL_FACEBOOK_CLIENT_ID;
QString CHANNEL_FACEBOOK_REDIRECTURL;
QString CHANNEL_FACEBOOK_SECRET;
//Chat Widget
QString CHAT_SOURCE_URL;
//Naver Shopping Live
QString CHANNEL_NAVER_SHOPPING_HOST;
QString CHANNEL_NAVER_SHOPPING_LIVE_LOGIN;
QString CHANNEL_NAVER_SHOPPING_LIVE_SMART_STORE_LOGIN;
QString CHANNEL_NAVER_SHOPPING_LIVE_STORE_CHANNEL_PRODUCT_SEARCH;
QString CHANNEL_NAVER_SHOPPING_LIVE_REFRESH_TOKEN;
QString CHANNEL_NAVER_SHOPPING_LIVE_PRODUCT_SEARCH_BY_URL;
QString CHANNEL_NAVER_SHOPPING_LIVE_PRODUCT_SEARCH_BY_TAG;
QString CHANNEL_NAVER_SHOPPING_LIVE_PRODUCT_SEARCH_BY_PRODUCTNOS;
QString CHANNEL_NAVER_SHOPPING_LIVE_CREATE_NOW_LIVING;
QString CHANNEL_NAVER_SHOPPING_LIVE_CREATE_SCHEDULE_LIVING;
QString CHANNEL_NAVER_SHOPPING_LIVE_STOP_LIVING;
QString CHANNEL_NAVER_SHOPPING_LIVE_UPDATE_LIVING;
QString CHANNEL_NAVER_SHOPPING_LIVE_SCHEDULE_LIST;
QString CHANNEL_NAVER_SHOPPING_LIVE_CATEGORY_LIST;
QString CHANNEL_NAVER_SHOPPING_LIVE_PSUH_NOTIFICATION;
QString CHANNEL_NAVER_SHOPPING_LIVE_GET_LIVING_INFO;
QString CHANNEL_NAVER_SHOPPING_LIVE_GET_SEESION_KEY;
QString CHANNEL_NAVER_SHOPPING_LIVE_DELETE_TOKEN;
int PRISM_NET_REQUEST_TIMEOUT;
int PRISM_NET_DOWNLOAD_TIMEOUT;
// youtube
const QString g_plsGoogleApiHost;
const QString g_plsYoutubeShareHost;
const QString g_plsYoutubeAPIHost;
const QString g_plsYoutubeShareUrl;
const QString g_plsYoutubeAPIHostV4;
const QString g_plsYoutubeChatUrl;
const QString g_plsYoutubeStudioManagerUrl;
//twitch
const QString g_plsTwitchApiHostUrl;
const QString g_plsTwitchChatUrl;
//vlive
QString const g_plsVliveSchedulePathUrl;
QString const g_plsVliveObjectUrl;
const QString g_exclusiveRtmpUrl;
//AfreecaTV
const QString CHANNEL_AFREECA_REDIRECTURL;
const QString CHANNEL_AFREECA_LOGIN;
const QString g_plsAfreecaTVShareUrl_beforeLive;
const QString g_plsAfreecaTVShareUrl_living;
const QString g_plsAfreecaTVChannelInfo;
const QString g_plsAfreecaTVUserNick;
const QString g_plsAfreecaTVDashboard;
const QString g_plsAfreecaTVCategories;
const QString g_plsAfreecaTVUpdate;
const QString g_plsAfreecaTVLiveID;
