

#!/bin/bash

OBS_ENV=$1
source ${OBS_ENV}

echo \
cmake -Wno-dev \
	 -S "${OBS_SRC_DIR}" \
     -B "${OBS_BUILD_DIR}" \
     -G "${GENERATOR}" \
	 -DCMAKE_BUILD_TYPE="${BUILD_TYPE}" \
	 -DCMAKE_PREFIX_PATH="${ALL_DEPS}" \
	 -DRELEASE_CANDIDATE=${VERSION}  \
     -DCOPIED_DEPENDENCIES=OFF \
     -DCOPY_DEPENDENCIES=ON \
     -DBUILD_CAPTIONS=ON \
	 -DBUILD_BROWSER=ON \
	 -DCEF_ROOT_DIR="${CEF_ROOT_DIR}" \
	 -DVIRTUALCAM_GUID="${VIRTUALCAM_GUID}" \
     -DVLC_PATH=${VLC_DIR} \
     -DENABLE_VLC=ON  \
	 -DCMAKE_OSX_DEPLOYMENT_TARGET=${PRISM_OSX_DEPLOYMENT_TARGET} \
	 -DCMAKE_OSX_ARCHITECTURES="${ARCH}" \
	 -DENABLE_UI=ON \
	 -DENABLE_WEBSOCKET=OFF \
	 -DOBS_BUNDLE_CODESIGN_IDENTITY="${CODESIGN_IDENT:--}" \
	 -DSWIG_DIR=${OBS_SWIG_DIR}


cmake -Wno-dev \
	 -S "${OBS_SRC_DIR}" \
     -B "${OBS_BUILD_DIR}" \
     -G "${GENERATOR}" \
	 -DCMAKE_BUILD_TYPE="${BUILD_TYPE}" \
	 -DCMAKE_PREFIX_PATH="${ALL_DEPS}" \
	 -DRELEASE_CANDIDATE=${VERSION}  \
     -DCOPIED_DEPENDENCIES=OFF \
     -DCOPY_DEPENDENCIES=ON \
     -DBUILD_CAPTIONS=ON \
	 -DBUILD_BROWSER=ON \
	 -DCEF_ROOT_DIR="${CEF_ROOT_DIR}" \
	 -DVIRTUALCAM_GUID="${VIRTUALCAM_GUID}" \
     -DVLC_PATH=${VLC_DIR} \
     -DENABLE_VLC=ON  \
	 -DCMAKE_OSX_DEPLOYMENT_TARGET=${PRISM_OSX_DEPLOYMENT_TARGET} \
	 -DCMAKE_OSX_ARCHITECTURES="${ARCH}" \
	 -DENABLE_UI=ON \
	 -DENABLE_WEBSOCKET=OFF \
	 -DOBS_BUNDLE_CODESIGN_IDENTITY="${CODESIGN_IDENT:--}" \
	 -DSWIG_DIR=${OBS_SWIG_DIR}



