# CONFIG SRC_PATH DEV_OUTPUT_PATH BINARY_SRC_PATH BINARY_OUTPUT_PATH ARCH TARGET OS_WINDOWS OS_MACOS

message(STATUS "Copy binary target.")
message(STATUS "CONFIG=${CONFIG}")
message(STATUS "SRC_PATH=${SRC_PATH}")
message(STATUS "DEV_OUTPUT_PATH=${DEV_OUTPUT_PATH}")
message(STATUS "BINARY_SRC_PATH=${BINARY_SRC_PATH}")
message(STATUS "BINARY_OUTPUT_PATH=${BINARY_OUTPUT_PATH}")
message(STATUS "ARCH=${ARCH}")
message(STATUS "TARGET=${TARGET}")
message(STATUS "OS_WINDOWS=${OS_WINDOWS}")
message(STATUS "OS_MACOS=${OS_MACOS}")

if(${CONFIG} STREQUAL "Debug")
    set(OUTPUT_PATH "${DEV_OUTPUT_PATH}/Debug")
else()
    set(OUTPUT_PATH "${DEV_OUTPUT_PATH}/Release")
endif()

function(copy_target src_path dest_path)
    if (EXISTS "${src_path}")
        if (IS_DIRECTORY "${src_path}")
            if(EXISTS "${src_path}/${CONFIG}/${TARGET}.exe")
                message(STATUS "${src_path}/${CONFIG}/${TARGET}.exe" -> "${dest_path}")
                file(COPY "${src_path}/${CONFIG}/${TARGET}.exe" DESTINATION "${dest_path}")
            elseif(EXISTS "${src_path}/${CONFIG}/${TARGET}d.exe")
                message(STATUS "${src_path}/${CONFIG}/${TARGET}d.exe" -> "${dest_path}")
                file(COPY "${src_path}/${CONFIG}/${TARGET}d.exe" DESTINATION "${dest_path}")
            elseif(EXISTS "${src_path}/${TARGET}.exe")
                message(STATUS "${src_path}/${TARGET}.exe" -> "${dest_path}")
                file(COPY "${src_path}/${TARGET}.exe" DESTINATION "${dest_path}")
            elseif(EXISTS "${src_path}/${TARGET}d.exe")
                message(STATUS "${src_path}/${TARGET}d.exe" -> "${dest_path}")
                file(COPY "${src_path}/${TARGET}d.exe" DESTINATION "${dest_path}")
            elseif(${CONFIG} STREQUAL "RelWithDebInfo")
                if(EXISTS "${src_path}/Release/${TARGET}.exe")
                    message(STATUS "${src_path}/Release/${TARGET}.exe" -> "${dest_path}")
                    file(COPY "${src_path}/Release/${TARGET}.exe" DESTINATION "${dest_path}")
                elseif(EXISTS "${src_path}/Release/${TARGET}d.exe")
                    message(STATUS "${src_path}/Release/${TARGET}d.exe" -> "${dest_path}")
                    file(COPY "${src_path}/Release/${TARGET}d.exe" DESTINATION "${dest_path}")
                endif()
            endif()

            if(EXISTS "${src_path}/${CONFIG}/${TARGET}.dll")
                message(STATUS "${src_path}/${CONFIG}/${TARGET}.dll" -> "${dest_path}")
                file(COPY "${src_path}/${CONFIG}/${TARGET}.dll" DESTINATION "${dest_path}")
            elseif(EXISTS "${src_path}/${CONFIG}/${TARGET}d.dll")
                message(STATUS "${src_path}/${CONFIG}/${TARGET}d.dll" -> "${dest_path}")
                file(COPY "${src_path}/${CONFIG}/${TARGET}d.dll" DESTINATION "${dest_path}")
            elseif(EXISTS "${src_path}/${TARGET}.dll")
                message(STATUS "${src_path}/${TARGET}.dll" -> "${dest_path}")
                file(COPY "${src_path}/${TARGET}.dll" DESTINATION "${dest_path}")
            elseif(EXISTS "${src_path}/${TARGET}d.dll")
                message(STATUS "${src_path}/${TARGET}d.dll" -> "${dest_path}")
                file(COPY "${src_path}/${TARGET}d.dll" DESTINATION "${dest_path}")
            elseif(${CONFIG} STREQUAL "RelWithDebInfo")
                if(EXISTS "${src_path}/Release/${TARGET}.dll")
                    message(STATUS "${src_path}/Release/${TARGET}.dll" -> "${dest_path}")
                    file(COPY "${src_path}/Release/${TARGET}.dll" DESTINATION "${dest_path}")
                elseif(EXISTS "${src_path}/Release/${TARGET}d.dll")
                    message(STATUS "${src_path}/Release/${TARGET}d.dll" -> "${dest_path}")
                    file(COPY "${src_path}/Release/${TARGET}d.dll" DESTINATION "${dest_path}")
                endif()
            endif()

            if(EXISTS "${src_path}/${CONFIG}/${TARGET}.pdb")
                message(STATUS "${src_path}/${CONFIG}/${TARGET}.pdb" -> "${dest_path}")
                file(COPY "${src_path}/${CONFIG}/${TARGET}.pdb" DESTINATION "${dest_path}")
            elseif(EXISTS "${src_path}/${CONFIG}/${TARGET}d.pdb")
                message(STATUS "${src_path}/${CONFIG}/${TARGET}d.pdb" -> "${dest_path}")
                file(COPY "${src_path}/${CONFIG}/${TARGET}d.pdb" DESTINATION "${dest_path}")
            elseif(EXISTS "${src_path}/${TARGET}.pdb")
                message(STATUS "${src_path}/${TARGET}.pdb" -> "${dest_path}")
                file(COPY "${src_path}/${TARGET}.pdb" DESTINATION "${dest_path}")
            elseif(EXISTS "${src_path}/${TARGET}d.pdb")
                message(STATUS "${src_path}/${TARGET}d.pdb" -> "${dest_path}")
                file(COPY "${src_path}/${TARGET}d.pdb" DESTINATION "${dest_path}")
            elseif(${CONFIG} STREQUAL "RelWithDebInfo")
                if(EXISTS "${src_path}/Release/${TARGET}.pdb")
                    message(STATUS "${src_path}/Release/${TARGET}.pdb" -> "${dest_path}")
                    file(COPY "${src_path}/Release/${TARGET}.pdb" DESTINATION "${dest_path}")
                elseif(EXISTS "${src_path}/Release/${TARGET}d.pdb")
                    message(STATUS "${src_path}/Release/${TARGET}d.pdb" -> "${dest_path}")
                    file(COPY "${src_path}/Release/${TARGET}d.pdb" DESTINATION "${dest_path}")
                endif()
            endif()
        else()
            message(STATUS "${src_path}" -> "${dest_path}")
            file(COPY "${src_path}" DESTINATION "${dest_path}")
        endif()
    else()
        if(EXISTS "${CMAKE_CURRENT_BINARY_DIR}/${CONFIG}/${TARGET}.exe")
            message(STATUS "${CMAKE_CURRENT_BINARY_DIR}/${CONFIG}/${TARGET}.exe" -> "${dest_path}")
            file(COPY "${CMAKE_CURRENT_BINARY_DIR}/${CONFIG}/${TARGET}.exe" DESTINATION "${dest_path}")
        endif()

        if(EXISTS "${CMAKE_CURRENT_BINARY_DIR}/${CONFIG}/${TARGET}.dll")
            message(STATUS "${CMAKE_CURRENT_BINARY_DIR}/${CONFIG}/${TARGET}.dll" -> "${dest_path}")
            file(COPY "${CMAKE_CURRENT_BINARY_DIR}/${CONFIG}/${TARGET}.dll" DESTINATION "${dest_path}")
        endif()

        if(EXISTS "${CMAKE_CURRENT_BINARY_DIR}/${CONFIG}/${TARGET}.pdb")
            message(STATUS "${CMAKE_CURRENT_BINARY_DIR}/${CONFIG}/${TARGET}.pdb" -> "${dest_path}")
            file(COPY "${CMAKE_CURRENT_BINARY_DIR}/${CONFIG}/${TARGET}.pdb" DESTINATION "${dest_path}")
        endif()
    endif()
endfunction()

if(IS_ABSOLUTE "${BINARY_SRC_PATH}")
    if(IS_ABSOLUTE "${BINARY_OUTPUT_PATH}")
        copy_target("${BINARY_SRC_PATH}" "${BINARY_OUTPUT_PATH}")
    else()
        copy_target("${BINARY_SRC_PATH}" "${OUTPUT_PATH}/${BINARY_OUTPUT_PATH}")
    endif()
elseif(BINARY_SRC_PATH)
    if (IS_ABSOLUTE "${BINARY_OUTPUT_PATH}")
        copy_target("${SRC_PATH}/${BINARY_SRC_PATH}" "${BINARY_OUTPUT_PATH}")
    else()
        copy_target("${SRC_PATH}/${BINARY_SRC_PATH}" "${OUTPUT_PATH}/${BINARY_OUTPUT_PATH}")
    endif()
else()
    if (IS_ABSOLUTE "${BINARY_OUTPUT_PATH}")
        copy_target("" "${BINARY_OUTPUT_PATH}")
    else()
        copy_target("" "${OUTPUT_PATH}/${BINARY_OUTPUT_PATH}")
    endif()
endif()
