# CONFIG SRC_PATH DEV_OUTPUT_PATH DATA_SRC_PATH DATA_OUTPUT_PATH ARCH TARGET OS_WINDOWS OS_MACOS

message(STATUS "Copy target data.")
message(STATUS "CONFIG=${CONFIG}")
message(STATUS "SRC_PATH=${SRC_PATH}")
message(STATUS "DEV_OUTPUT_PATH=${DEV_OUTPUT_PATH}")
message(STATUS "DATA_SRC_PATH=${DATA_SRC_PATH}")
message(STATUS "DATA_OUTPUT_PATH=${DATA_OUTPUT_PATH}")
message(STATUS "ARCH=${ARCH}")
message(STATUS "TARGET=${TARGET}")
message(STATUS "OS_WINDOWS=${OS_WINDOWS}")
message(STATUS "OS_MACOS=${OS_MACOS}")

if(${CONFIG} STREQUAL "Debug")
    set(OUTPUT_PATH "${DEV_OUTPUT_PATH}/Debug")
else()
    set(OUTPUT_PATH "${DEV_OUTPUT_PATH}/Release")
endif()

function(copy_file src_path dest_path)
    if (NOT EXISTS "${src_path}")
        return()
    endif()

    if (IS_DIRECTORY "${src_path}")
        file(GLOB data_files "${src_path}/*")
        foreach(data_file ${data_files})
            message(STATUS "${data_file} -> ${dest_path}")
            file(COPY "${data_file}" DESTINATION "${dest_path}")
        endforeach()
    else()
        message(STATUS "${src_path} -> ${dest_path}")
        file(COPY "${src_path}" DESTINATION "${dest_path}")
    endif()
endfunction()


if (IS_ABSOLUTE "${DATA_SRC_PATH}")
    if (IS_ABSOLUTE "${DATA_OUTPUT_PATH}")
        copy_file("${DATA_SRC_PATH}" "${DATA_OUTPUT_PATH}")
    else()
        copy_file("${DATA_SRC_PATH}" "${OUTPUT_PATH}/${DATA_OUTPUT_PATH}")
    endif()
else()
    if (IS_ABSOLUTE "${DATA_OUTPUT_PATH}")
        copy_file("${SRC_PATH}/${DATA_SRC_PATH}" "${DATA_OUTPUT_PATH}")
    else()
        copy_file("${SRC_PATH}/${DATA_SRC_PATH}" "${OUTPUT_PATH}/${DATA_OUTPUT_PATH}")
    endif()
endif()
