# CONFIG QT_DIR DEV_OUTPUT_DIR TARGET OS_WINDOWS OS_MACOS

message(STATUS "deploy target qt libraries.")
message(STATUS "CONFIG=${CONFIG}")
message(STATUS "QT_DIR=${QT_DIR}")
message(STATUS "DEV_OUTPUT_DIR=${DEV_OUTPUT_DIR}")
message(STATUS "TARGET=${TARGET}")
message(STATUS "OS_WINDOWS=${OS_WINDOWS}")
message(STATUS "OS_MACOS=${OS_MACOS}")
message(STATUS "VS_WINDOWS_TARGET_PLATFORM_VERSION=${VS_WINDOWS_TARGET_PLATFORM_VERSION}")

if(${CONFIG} STREQUAL "Debug")
    set(OUTPUT_DIR "${DEV_OUTPUT_DIR}/Debug")
else()
    set(OUTPUT_DIR "${DEV_OUTPUT_DIR}/Release")
endif()

set(D3DCompiler_47_SRC_PATH "C:/Program Files (x86)/Windows Kits/10/bin/${VS_WINDOWS_TARGET_PLATFORM_VERSION}/x64/D3DCompiler_47.dll")

function(copy_d3dcompiler_47 target_dir)
	if (EXISTS "${D3DCompiler_47_SRC_PATH}")
		message(STATUS "Copy File ${D3DCompiler_47_SRC_PATH} -> ${target_dir}/D3DCompiler_47.dll")
		execute_process(COMMAND "${CMAKE_COMMAND}" -E copy "${D3DCompiler_47_SRC_PATH}" "${target_dir}/D3DCompiler_47.dll")
	endif()
endfunction()

if (OS_WINDOWS)
	if (EXISTS "${OUTPUT_DIR}/${TARGET}.exe")
		execute_process(COMMAND "${QT_DIR}/bin/windeployqt.exe" "${OUTPUT_DIR}/${TARGET}.exe" --no-translations --no-system-d3d-compiler)
		copy_d3dcompiler_47("${OUTPUT_DIR}")
	elseif (EXISTS "${OUTPUT_DIR}/${TARGET}.dll")
		execute_process(COMMAND "${QT_DIR}/bin/windeployqt.exe" "${OUTPUT_DIR}/${TARGET}.dll" --no-translations --no-system-d3d-compiler)
		copy_d3dcompiler_47("${OUTPUT_DIR}")
	elseif (EXISTS "${OUTPUT_DIR}/bin/64bit/${TARGET}.exe")
		execute_process(COMMAND "${QT_DIR}/bin/windeployqt.exe" "${OUTPUT_DIR}/bin/64bit/${TARGET}.exe" --no-translations --no-system-d3d-compiler)
		copy_d3dcompiler_47("${OUTPUT_DIR}/bin/64bit")
	elseif (EXISTS "${OUTPUT_DIR}/bin/64bit/${TARGET}.dll")
		execute_process(COMMAND "${QT_DIR}/bin/windeployqt.exe" "${OUTPUT_DIR}/bin/64bit/${TARGET}.dll" --no-translations --no-system-d3d-compiler)
		copy_d3dcompiler_47("${OUTPUT_DIR}/bin/64bit")
	endif()
endif()
