#ifndef NETWORKACCESSMANAGER_GLOBAL_H
#define NETWORKACCESSMANAGER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(NETWORKACCESSMANAGER_LIBRARY)
#define NETWORKACCESSMANAGER_EXPORT Q_DECL_EXPORT
#else
#define NETWORKACCESSMANAGER_EXPORT Q_DECL_IMPORT
#endif

#endif // NETWORKACCESSMANAGER_GLOBAL_H
