#if !defined(_PRISM_COMMON_LIBLOG_LIBLOG_ACTION_H)
#define _PRISM_COMMON_LIBLOG_LIBLOG_ACTION_H

#define ACTION_LBUTTON "Mouse Left Button"
#define ACTION_RBUTTON "Mouse Right Button"
#define ACTION_CLICK "Click"
#define ACTION_DBCLICK "DbClick"
#define ACTION_DROP "Drop"
#define ACTION_SLIDER "Slider"
#define ACTION_DRAG "Drag"

#define ACTION_LBUTTON_CLICK ACTION_LBUTTON " " ACTION_CLICK
#define ACTION_RBUTTON_CLICK ACTION_RBUTTON " " ACTION_CLICK
#define ACTION_LBUTTON_DBCLICK ACTION_LBUTTON " " ACTION_DBCLICK
#define ACTION_RBUTTON_DBCLICK ACTION_RBUTTON " " ACTION_DBCLICK

#endif // _PRISM_COMMON_LIBLOG_LIBLOG_ACTION_H
