#pragma once

#include <QObject>
#include <QDialogButtonBox>
#include <QNetworkReply>
#include <QJsonObject>
#include <vector>
#include "frontend-api-global.h"
#include "PLSAlertView.h"
#include "libhttp-client.h"
#include <mutex>
#include <shared_mutex>

FRONTEND_API extern const QString PLSErrPhaseChannel;
FRONTEND_API extern const QString PLSErrPhaseLogin;
FRONTEND_API extern const QString PLSErrPhaseDashBoard;

FRONTEND_API extern const QString PLSErrCustomKey_LoadLiveInfoFailed;
FRONTEND_API extern const QString PLSErrCustomKey_StartLiveFailed_Single;
FRONTEND_API extern const QString PLSErrCustomKey_StartLiveFailed_Multi;
FRONTEND_API extern const QString PLSErrCustomKey_UpdateLiveInfoFailed;
FRONTEND_API extern const QString PLSErrCustomKey_StartRehearsalFailed;
FRONTEND_API extern const QString PLSErrCustomKey_LoadLiveInfoExpired;
FRONTEND_API extern const QString PLSErrCustomKey_UpdateLiveInfoFailedNoService;
FRONTEND_API extern const QString PLSErrCustomKey_SOOPUpdateLiveInfoFailed;
FRONTEND_API extern const QString PLSErrCustomKey_SOOPLoadLiveInfoFailed;
FRONTEND_API extern const QString PLSErrCustomKey_UploadImageFailed;
FRONTEND_API extern const QString PLSErrCustomKey_OutputRecordFailed;
FRONTEND_API extern const QString PLSErrCustomKey_PRISMTempError;

FRONTEND_API extern const QString PLSErrApiKey_OutputRecord;
FRONTEND_API extern const QString PLSErrApiKey_OutputStream;
FRONTEND_API extern const QString PLSErrKeyAllAlert;

class FRONTEND_API PLSErrorHandler : public QObject {
	Q_OBJECT

public:
	enum class AlertType {
		Error = 0, //contact us
		Error_Blog,
		Error_Link,
		Error_Blog_Link,
		Normal, //normal
		Normal_Code,
		Normal_Code_Blog,
		Normal_Code_Link
	};
	Q_ENUM(AlertType)

	enum class ErrorType {
		Other = -1,
		TokenExpired = 0,
	};
	Q_ENUM(ErrorType)

	enum ErrCode {
		INVALID = -1,
		SUCCESS = 0,

		//Common
		COMMON_NETWORK_ERROR = 10000,
		COMMON_UNKNOWN_ERROR = 10001,
		COMMON_TOKEN_EXPIRED_ERROR = 10002,
		COMMON_CHANNEL_LOGIN_TOKEN_EXPIRED_ERROR = 10003,
		COMMON_CHANNEL_LOGIN_FAIL = 10004,
		COMMON_CHANNEL_EMPTYCHANNEL,
		//Common default
		COMMON_DEFAULT_LOADLIVEINFOFAILED = 10500,
		COMMON_DEFAULT_STARTLIVEFAILED_SINGLE,
		COMMON_DEFAULT_STARTLIVEFAILED_MULTI,
		COMMON_DEFAULT_UPDATELIVEINFOFAILED,
		COMMON_DEFAULT_STARTREHEARSALFAILED,
		COMMON_DEFAULT_FAILEDTOSTARTLIVE,
		COMMON_DEFAULT_TIMEOUTTRYAGAIN,
		COMMON_DEFAULT_UPLOADIMAGEFAILED,
		COMMON_DEFAULT_SERVERERRORTRYAGAIN,
		COMMON_DEFAULT_TEMPERRORTRYAGAIN,
		COMMON_DEFAULT_NAVERTVUNKNOWN,
		COMMON_DEFAULT_PRISMLOGINFAILEDAGAIN,
		COMMON_DEFAULT_B2BLOGINFAILEDAGAIN,
		COMMON_DEFAULT_FAILEDBECAUSECONNECTION,
		COMMON_DEFAULT_OUTPUT_RECORD_ERROR,
		COMMON_DEFAULT_UPDATELIVEINFOFAILED_NOSERVICE,
		COMMON_DEFAULT_MQTT_BROADCAST_END,
		COMMON_DEFAULT_PRISM_TEMP_ERROR,

		PRISM_API_INIT = 11000,
		PRISM_API_TOKEN_EXPIRED = 11001,
		PRISM_API_SYSTEM_TIME_ERROR = 11002,

		//Email
		PRISM_LOGIN_EMAIL_NOT_EXIST_USER = 25000,
		PRISM_LOGIN_EMAIL_RESTRICT_USER,
		PRISM_LOGIN_EMAIL_PW_FAIL,
		PRISM_LOGIN_EMAIL_RETRY_EXCEED,
		PRISM_LOGIN_EMAIL_UNSUPPORTED_METHOD,
		PRISM_LOGIN_EMAIL_SIGN_USER_EXIST,
		PRISM_LOGIN_EMAIL_SIGN_NVALID_PASSWORD,
		PRISM_LOGIN_EMAIL_RESET_PWD_NOT_FOUND_EMAIL,
		PRISM_LOGIN_EMAIL_CHANGE_PWD_SAME,
		PRISM_LOGIN_EMAIL_CHANGE_PWD_NOT_MATCH,

		//YouTube
		CHANNEL_YOUTUBE_NOTFOUND_404_CHANNELNOTFOUND = 28000,
		CHANNEL_YOUTUBE_INVALIDVALUE_400_INVALIDDESCRIPTION = 28001,
		CHANNEL_YOUTUBE_INVALIDVALUE_400_INVALIDLATENCYPREFERENCEOPTIONS = 28002,
		CHANNEL_YOUTUBE_FORBIDDEN_403_INVALIDTRANSITION = 28003,
		CHANNEL_YOUTUBE_LIVEBROADCASTNOTFOUND,
		CHANNEL_YOUTUBE_INSUFFICIENTPERMISSIONS_LIVEPERMISSIONBLOCKED,
		CHANNEL_YOUTUBE_INSUFFICIENTPERMISSIONS_LIVESTREAMINGNOTENABLED,
		CHANNEL_YOUTUBE_403_MADEFORKIDSMODIFICATIONNOTALLOWED,
		CHANNEL_YOUTUBE_FORBIDDEN_403_REDUNDANTTRANSITION = 28008,
		CHANNEL_YOUTUBE_VIDEONOTFOUND,
		CHANNEL_YOUTUBE_CUSTOM_REMOTEINVALID = 28010,
		CHANNEL_YOUTUBE_CUSTOM_BROADCASTTYPENOTSUPPORT = 28011,
		CHANNEL_YOUTUBE_CUSTOM_LATENCYCHANGEFAILED,
		CHANNEL_YOUTUBE_LIVESTREAMNOTFOUND,
		CHANNEL_YOUTUBE_AUTHENTICATEDUSERACCOUNTSUSPENDED,
		CHANNEL_YOUTUBE_BACKENDERROR,
		CHANNEL_YOUTUBE_TITLE_CONTAIN_SPECIAL = 28016,
		CHANNEL_YOUTUBE_DESCRIPTION_TOO_LONG = 28017,
		CHANNEL_YOUTUBE_REHEARSAL_SWITCH_TO_LIVE = 28018,
		CHANNEL_YOUTUBE_AUTOSTART_RTMP = 28019,
		CHANNEL_YOUTUBE_AUTOSTART_CHANNEL = 28020,
		CHANNEL_YOUTUBE_AUTOSTART_BOTH = 28021,

		// NaverShoppingLive
		CHANNEL_NAVER_SHOPPING_LIVE_INVALID_SCHEDULE = 30000,
		CHANNEL_NAVER_SHOPPING_LIVE_OTHER_STORE_BAD_REQUEST,
		CHANNEL_NAVER_SHOPPING_LIVE_UNAUTHORIZED,
		CHANNEL_NAVER_SHOPPING_LIVE_TOKEN_EXPIRED,
		CHANNEL_NAVER_SHOPPING_LIVE_LIVE_COMMERCE_UNAUTHORIZED,
		CHANNEL_NAVER_SHOPPING_LIVE_CREATE_UNAUTHORIZED,
		CHANNEL_NAVER_SHOPPING_LIVE_UNAUTHORIZED_REASON_BLOCK,
		CHANNEL_NAVER_SHOPPING_LIVE_AUTH_FAILED,
		CHANNEL_NAVER_SHOPPING_LIVE_AUTH_TEMPORARY_FAILED,
		CHANNEL_NAVER_SHOPPING_LIVE_NOT_SUPPORT_STORE,
		CHANNEL_NAVER_SHOPPING_LIVE_BROADCAST_STARTS_EARLIER,
		CHANNEL_NAVER_SHOPPING_LIVE_INVALID_STREAM_ORIGIN_TYPE,
		CHANNEL_NAVER_SHOPPING_LIVE_UPDATE_LIVE_INFO_FAILED,
		CHANNEL_NAVER_SHOPPING_LIVE_UPDATE_SCHEDULE_INFO_FAILED,
		CHANNEL_NAVER_SHOPPING_LIVE_RESERVATION_IS_LIVED,
		CHANNEL_NAVER_SHOPPING_LIVE_CREATE_SCHEDULE_LIVING_FAILED,
		CHANNEL_NAVER_SHOPPING_LIVE_REFRESH_LIVEINFO_FAILED,
		CHANNEL_NAVER_SHOPPING_LIVE_ADD_AGE_RESTRICT_FAILED,
		CHANNEL_NAVER_SHOPPING_LIVE_UPLOAD_IMAGE_FAILED,
		CHANNEL_NAVER_SHOPPING_LIVE_GET_CATEGORY_LIST_FAILED,
		CHANNEL_NAVER_SHOPPING_LIVE_ATTACH_PRODUCTS_TO_OWN_MALL,
		CHANNEL_NAVER_SHOPPING_LIVE_ADD_UNATTACHABLE_PRODUCT_FAILED,
		CHANNEL_NAVER_SHOPPING_LIVE_SEND_NOTIFICATION_FAILED,
		CHANNEL_NAVER_SHOPPING_LIVE_SCHEDULE_CHANGED_FAILED,
		CHANNEL_NAVER_SHOPPING_LIVE_ACCOUNT_EXPIRED,
		CHANNEL_NAVER_SHOPPING_LIVE_REFRESH_UNKNOWN_ERROR,
		CHANNEL_NAVER_SHOPPING_LIVE_FINISHED_BY_PLATFORM,
		CHANNEL_NAVER_SHOPPING_LIVE_GET_SMART_STORE_URL_FAILED,

		//AfreecaTV
		CHANNEL_AFREECATV_LOGIN_EXPIRED = COMMON_CHANNEL_LOGIN_TOKEN_EXPIRED_ERROR,
		CHANNEL_AFREECATV_LOGIN_ERROR = COMMON_CHANNEL_LOGIN_FAIL,
		CHANNEL_AFREECATV_EMPTYCHANNEL = COMMON_CHANNEL_EMPTYCHANNEL,
		CHANNEL_AFREECATV_NETWORK_ERROR = COMMON_NETWORK_ERROR,
		CHANNEL_AFREECATV_API_EXPIRED = COMMON_TOKEN_EXPIRED_ERROR,
		CHANNEL_AFREECATV_LOADAPI_FAIL = 34001,
		CHANNEL_AFREECATV_UPDATEAPI_FAIL = 34002,

		//PRISM
		PRISM_API_COUNTRY_FAILED = 11501,
		PRISM_API_NO_LONGER_VALID,
		PRISM_API_INVALID_PLATFORM,
		PRISM_API_TERM_OF_AGREE,
		PRISM_API_NO_APP_UPDATE,
		PRISM_API_NO_EXIST_USER,

		//RTMP
		CHANNEL_CUSTOM_RTMP_TOKEN_EXPIRED = PRISM_API_TOKEN_EXPIRED,
		CHANNEL_CUSTOM_RTMP_RUNTIMEEXCEPTION = 56001,
		CHANNEL_CUSTOM_RTMP_NOTEXIST = 56002,
		CHANNEL_CUSTOM_RTMP_SYSTEMTIMEERROR = PRISM_API_SYSTEM_TIME_ERROR,

		//Output/Recording (57000~57999)
		PRISM_OUTPUT_BAD_PATH = 57999,       //OBS_OUTPUT_BAD_PATH (-1)
		PRISM_OUTPUT_CONNECT_FAILED = 57998, //OBS_OUTPUT_CONNECT_FAILED (-2)
		PRISM_OUTPUT_ERROR = 57996,          //OBS_OUTPUT_ERROR (-4)
		PRISM_OUTPUT_DISCONNECTED = 57995,   //OBS_OUTPUT_DISCONNECTED (-5)
		PRISM_OUTPUT_UNSUPPORTED = 57994,    //OBS_OUTPUT_UNSUPPORTED (-6)
		PRISM_OUTPUT_NO_SPACE = 57993,       //OBS_OUTPUT_NO_SPACE (-7)
		PRISM_OUTPUT_ENCODE_ERROR = 57992,   //OBS_OUTPUT_ENCODE_ERROR (-8)
		PRISM_OUTPUT_INVALID_STREAM = 57997, //OBS_OUTPUT_INVALID_STREAM (-3)
		PRISM_OUTPUT_HDR_DISABLED = 57991,   //OBS_OUTPUT_HDR_DISABLED (-9)

		//BAND
		CHANNEL_BAND_FORBIDDEN_ERROR = 33002,
		CHANNEL_BAND_NO_PERMISSION_ERROR,
		CHANNEL_BAND_ALEARD_BOARDCAST,
		CHANNEL_BAND_OTHER_ERROR,

		//NaverTV
		CHANNEL_NAVERTV_LIVENOTFOUND = 32000,
		CHANNEL_NAVERTV_PERMITEXCEPTION,
		CHANNEL_NAVERTV_LIVESTATUSEXCEPTION,
		CHANNEL_NAVERTV_START30MINEXCEPTION,
		CHANNEL_NAVERTV_ALREADYONAIR,
		CHANNEL_NAVERTV_PAIDSPONSORSHIPINFO,
		CHANNEL_NAVERTV_AUTH_FAILED,

		//B2B
		PRISM_LOGIN_NCP_B2B_SERVICE_NOT_FOUND = 19000,
		PRISM_LOGIN_NCP_B2B_SERVICE_DELETED,
		PRISM_LOGIN_NCP_B2B_USERINFO_NO_EXIT,
		CHANNEL_NCP_B2B_1022_SERVICE_DELETED = 26000,
		CHANNEL_NCP_B2B_1101_SERVICE_DISABLED = 26001,
		CHANNEL_NCP_B2B_1102_CHANNEL_DISABLED = 26002,
		CHANNEL_NCP_B2B_1103_PARTNERCHANNELDISABLEDBYTRIAL = 26003,
		CHANNEL_NCP_B2B_1104_RESOURCE_NOT_FOUND = 26004,
		CHANNEL_NCP_B2B_401_PREPARELIVE = 26005,

		//CHZZK
		CHANNEL_CHZZK_1106_AGREEMENT_REQUIRED = 31000,
		CHANNEL_CHZZK_1102_LOGIN_AGREEMENT_REQUIRED = 31001,

		//Facebook
		CHANNEL_FACEBOOK_DECLINED = 29000,
		CHANNEL_FACEBOOK_DECLINED_60DAYS,
		CHANNEL_FACEBOOK_DECLINED_100FOLLOWERS,
		CHANNEL_FACEBOOK_INVALIDACCESSTOKEN,
		CHANNEL_FACEBOOK_OBJECTNOTEXIST,

		//MQTT
		MQTT_DUPLICATED = 12000,
		MQTT_NOTICE_LONG_BROADCAST,
		MQTT_PARTNER_SERVICE_DISABLED,

		//		General All Alert
		ALERT_DISCONNECT_WARNING = 60000,
		ALERT_CHANNEL_CHILD_EXCLUSIVE_CONFIRM,
		ALERT_CHANNEL_EXCLUSIVE_DISABLE_OTHER_CONFIRM,
		ALERT_CHANNEL_DISABLE_WHILE_LIVING_CONFIRM,
		ALERT_CHANNEL_DUAL_OUTPUT_EXCLUSIVE_WARNING,
		ALERT_CHANNEL_SELECTED_LIMITED,
		ALERT_GOLIVE_BUSY_STARTING_STREAM,
		ALERT_GOLIVE_BUSY_ENDING_STREAM,
		ALERT_GOLIVE_BUSY_STARTING_REHEARSAL,
		ALERT_GOLIVE_BUSY_ENDING_REHEARSAL,
		ALERT_GOLIVE_BUSY_STARTING_REC,
		ALERT_GOLIVE_BUSY_ENDING_REC,
		ALERT_GOLIVE_FORCE_STOP_CONFIRM,
		ALERT_GOLIVE_END_REHEARSAL_CONFIRM,
		ALERT_GOLIVE_END_LIVE_CONFIRM,
		ALERT_GOLIVE_ENCODER_MISMATCH_STREAMING_ADVANCED,
		ALERT_GOLIVE_ENCODER_MISMATCH_STREAMING_SIMPLE,
		ALERT_GOLIVE_ENCODER_MISMATCH_RECORDING_ADVANCED,
		ALERT_GOLIVE_ENCODER_MISMATCH_RECORDING_SIMPLE,
		ALERT_CHANNELS_REFRESH_DELETE_LIVE_INFO,
		ALERT_CHANNELS_MAX_CHANNELS_COUNT,
		ALERT_CHANNELS_VERSION_NEED_UPDATE,
		ALERT_CHANNELS_VERSION_SUGGEST_UPDATE,
		ALERT_CHANNELS_DUAL_OUTPUT_NO_BOTH_SELECTION,
		ALERT_CHANNELS_EMPTY_FOR_STREAM,
		ALERT_ENCODER_UNSUPPORTED_FOR_STREAM,
		ALERT_CHANNELS_EMPTY_SHARE_URL,
		ALERT_CHANNEL_RTMP_STREAMKEY_ERROR,
		ALERT_CHANNEL_RTMP_EXIST_NAME,
		ALERT_CHANNELS_SETTINGS_NO_CHANNEL_SELECTED,
		ALERT_CHANNELS_SETTINGS_AT_LEAST_ONE_FOR_CONNECT,
		ALERT_RESOLUTION_GUIDE_APPLY_RECOMMENDED_CONFIRM,
		ALERT_RESOLUTION_GUIDE_SET_FAILED_STREAM_RECORD,
		ALERT_RESOLUTION_GUIDE_SET_FAILED_VIRTUALCAM,
		ALERT_RESOLUTION_GUIDE_SET_FAILED_PLUGIN_OUTPUT,
		ALERT_LIVEINFO_AFREECA_TV_TITLE_LENGTH_MAX,
		ALERT_PLATFORM_PREPARE_LIVE_RESOLUTION_FPS_FAILED,
		ALERT_PLATFORM_DUAL_OUTPUT_NO_HORIZONTAL,
		ALERT_PLATFORM_DUAL_OUTPUT_NO_VERTICAL,
		ALERT_PLATFORM_MULTICAST_GREATER_1080,
		ALERT_PLATFORM_GREATER_1080_RECORDING_OR_VIRTUALCAM,
		ALERT_PLATFORM_PREPARE_LIVE_NETWORK_OFFLINE,
		ALERT_NCB2B_WATERMARK_RESOURCE_MISSING,
		ALERT_BROADCAST_BITRATE_TOO_HIGH,
		ALERT_MQTT_MAX_LIVE_TIME_SHOPPING_BAND_END,
		ALERT_MQTT_MAX_LIVE_TIME_GENERAL_PLATFORM_END,
		ALERT_NAVERSHOPPING_LIVE_TIME_END_NOW,
		ALERT_MQTT_LIVE_FINISHED_BY_PLATFORM_CONFIRM,
		ALERT_MQTT_REQUEST_BROADCAST_END_CONFIRM,
		ALERT_LIVE_STOPPED_BY_REMOTE_SIMULCAST,
		ALERT_CHANNEL_CRASH_RECOVERY_RESUME_STREAMING,
		ALERT_CHANNELS_RTMP_URL_INVALID,
		ALERT_UPDATE_FORCE_VIRTUAL_CAM_ACTIVE,
		ALERT_CHZZK_SPONSOR_GET_URL_FAIL,
		ALERT_DUAL_OUTPUT_CLOSE_STUDIO_MODE_CONFIRM,
		ALERT_DUAL_OUTPUT_THIRD_PLUGIN_IN_USING,
		ALERT_LIVE_ABORT_STREAM_ACTIVE,
		ALERT_CONFIRM_STOP_RECORD,
		ALERT_VIRTUALCAM_UNAVAILABLE,
		ALERT_RESIZE_OUTPUT_SIZE_OF_SOURCE,
		ALERT_OUTPUT_BAD_PATH,
		ALERT_REPLAY_BUFFER_PAUSE_WARNING,

		ALERT_TAKE_PHOTO_NULL = 60500,
		ALERT_SELECT_IMAGE_PHOTO_TOO_SMALL = 60501,
		ALERT_SELECT_IMAGE_PHOTO_TOO_LARGE = 60502,
		ALERT_LIVEINFO_TITLE_TOO_LONG = 60503,
		ALERT_CHZZK_CATEGORY_INVALID = 60504,
		ALERT_SOURCE_LENS_UPGRADE_NOTICE = 60506,
		ALERT_PROPERTIES_CONFIRM_RESET = 60507,
		ALERT_PROPERTIES_CONFIRM_QUIT = 60508,
		ALERT_DOCK_CLOSE_WARNING = 60509,
		ALERT_PAYMENT_EXPIRED_PLUS = 60510,
		ALERT_PAYMENT_EXPIRED_TRIAL = 60511,
		ALERT_PAYMENT_RESTART_GOLIVE = 60512,
		ALERT_PAYMENT_RESTART_SETTING = 60513,
		ALERT_PROPERTIES_URL_OPEN_CONFIRM = 60514,

		ALERT_BASIC_RESOURCE_DOWNLAOD_FAILED_RETRY = 61000,
		ALERT_SCENE_COLLECTION_IMPORT_ERROR = 61001,
		ALERT_SCENE_COLLECTION_IMPORT_NOTFOUND = 61002,
		ALERT_SCENE_REALTIME_LIMIT_TIPS = 61003,
		ALERT_NAMEEXISTS_TEXT = 61004,
		ALERT_NAVERSHOPPING_LIVEINFO_SCHEDULE_SWITCH_TIP = 61005,
		ALERT_NAVERSHOPPING_LIVEINFO_SCHEDULE_INFO_EMPTY_TIP = 61006,
		ALERT_LIVEINFO_TITLE_LENGTH_CHECK_ARG = 61007,
		ALERT_NAVERSHOPPING_LIVEINFO_MAX_SUMMARY_LENGTH = 61008,
		ALERT_NAVERSHOPPINGLIVE_LIVEINFO_REMOVEAGELIMITPRODUCTS = 61009,
		ALERT_NAVERSHOPPINGLIVE_LIVEINFO_PRODUCT_ATLEASTONE = 61010,
		ALERT_NAVERSHOPPINGLIVE_LIVEINFO_FIXPRODUCT_LIMIT = 61011,
		ALERT_NAVERSHOPPINGLIVE_PRODUCTDIALOG_STORE_CHANGESTOREALERT = 61012,
		ALERT_NAVERSHOPPINGLIVE_LIVEINFO_LIVE_PRODUCTS_UNATTACHABLE = 61013,
		ALERT_NAVERSHOPPING_LIVEINFO_AGE_RESTRICT_PRODUCT = 61014,
		ALERT_NAVERSHOPPINGLIVE_LIVEINFO_LIVE_PRODUCTS_EXISTED = 61015,
		ALERT_NAVERSHOPPINGLIVE_PRODUCTDIALOG_ADDPRODUCT_LIMIT = 61016,
		ALERT_NAVERSHOPPING_NO_SUPPORT_HORIZONTAL_MODE_TIP = 61017,
		ALERT_NAVERSHOPPING_NO_SUPPORT_RESOLUTION_MODE_TIP = 61018,
		ALERT_NAVERSHOPPING_LIVEINFO_CHOOSE_SCHEDULE_CHANGED_TIP = 61019,
		ALERT_NAVERSHOPPING_COPYRIGHT_ALERT_TITLE = 61020,
		ALERT_NONAMEENTERED_TEXT = 61021,
		ALERT_ADDURL_TEXT = 61022,
		ALERT_BASIC_MAINMENU_PROFILE_EXISTS_IMPORT = 61023,
		ALERT_CONFIRMREMOVE_TEXT_BODY = 61024,
		ALERT_BASIC_MAIN_REMIGRATESCENECOLLECTION_CANNOTMIGRATE_ACTIVE = 61025,
		ALERT_BASIC_MAIN_REMIGRATESCENECOLLECTION_CANNOTMIGRATE_UNKNOWNBASERESOLUTION = 61026,
		ALERT_BASIC_MAIN_REMIGRATESCENECOLLECTION_CANNOTMIGRATE_FAILEDVIDEORESET = 61027,
		ALERT_BASIC_MAIN_REMIGRATESCENECOLLECTION_CANNOTMIGRATE_BASERESOLUTIONMATCHES = 61028,
		ALERT_BASIC_MAIN_REMIGRATESCENECOLLECTION_TEXT = 61029,
		ALERT_SOURCELEAK_TEXT = 61030,
		ALERT_IMPORTER_AUTOMATICCOLLECTIONTEXT = 61031,
		ALERT_MISSINGFILES_AUTOSEARCHTEXT = 61032,
		ALERT_EXPORT_SCENE_TEMPLATE = 61033,
		ALERT_SCENETEMPLATE_INSTALL_SOURCE_HAS_UPDATE_TIP = 61034,
		ALERT_SCENETEMPLATE_INSTALL_SOURCE_NOT_FOUND_ERROR = 61035,
		ALERT_SCENETEMPLATE_VERTICAL_TEMPLATE = 61036,
		ALERT_SCENETEMPLATE_INSTALL_COMMON_ERROR = 61037,
		ALERT_LOGIN_CHECK_NOTE_NETWORK = 61038,
		ALERT_VIRTUAL_RESOURCE_LOCALFILE_DISAPPEAR_TIP = 61039,
		ALERT_VIRTUAL_RESOURCE_FILE_DISAPPAER_TIP = 61040,
		ALERT_VIRTUAL_MYLIST_DELETEALL_POPUP = 61041,
		ALERT_VIRTUAL_RESOURCE_FILE_USING_DELETE_TIP = 61042,
		ALERT_VIRTUAL_RESOURCE_FILE_DELETE_TIP = 61043,
		ALERT_VIRTUAL_RESOURCE_PART_DOWNLOAD_FAILED = 61044,
		ALERT_VIRTUAL_RESOURCE_ADD_FILE_OTHER_ERROR_TIP = 61045,
		ALERT_VIRTUAL_RESOURCE_ADD_FILE_EXCEED_TIP = 61046,
		ALERT_NAVERSHOPPING_GOLIVE_RESOLUTION_FPS_INVALID = 61047,

		//
		ALERT_LABORATORY_ITEM_OPEN_OTHER_REASON_FAILED_TEXT_0 = 61500,
		ALERT_LABORATORY_ITEM_OPEN_OTHER_REASON_FAILED_TEXT_1,
		ALERT_LABORATORY_ITEM_OPEN_NETWORK_FAILED_TEXT,
		ALERT_LABORATORY_ITEM_OPEN_RESTART_TEXT,
		ALERT_LABORATORY_ITEM_INSTALL_FINISHED_RESTART_APP_CONTENT,
		ALERT_SETTINGS_NEED_RESTART,
		ALERT_BROADCAST_INVALID_SCHEDULE,
		ALERT_LIVEINFO_TITLE_LENGTH_CHECK_ARG_NAVERTV,
		ALERT_OUTPUT_BADPATH_TEXT,
		ALERT_BASIC_SETTINGS_CONFIRM,
		ALERT_SETTINGS_GENERAL_LANGUAGE_CHANGED,
		ALERT_CODEC_COMPACT_CODEC_MISSING_ONEXIT_TEXT,
		ALERT_CODEC_COMPACT_CONTAINER_MISSING_ONEXIT_TEXT,
		ALERT_OUTPUT_WARNINGS_NOTRACKS_SELECTED_ONEXIT_TEXT,
		ALERT_RESOLUTION_VIRTUALCAM_ACTIVED,
		ALERT_SETTINGS_RESET_QUESTION,
		ALERT_BASIC_SETTINGS_GENERAL_HIDE_OBS_CAPTURE_MESSAGE,
		ALERT_SETTINGS_PROGRAME_RESTART,
		ALERT_SETTINGS_AUDIO_LOW_LATENCY,
		ALERT_SETTINGS_OUTPUT_SIMPLE_WARN_LOSSLESS,
		ALERT_REMUX_EXIT_UNFINISHED,
		ALERT_REMUX_NOFILES_ADDED,
		ALERT_REMUX_FILEEXISTS,
		ALERT_FINISHED,
		ALERT_FINISHED_ERROR,
		ALERT_LIVEINFO_LIVE_ERROR_STOPED_BYREMOTE,

		//TERMS
		ALERT_PAY_TERMS_AGREE = 62000,
		//FACEBOOK
		ALERT_FACEBOOK_TITLE_MAX_LENGTH,
		ALERT_FACEBOOK_GROUP_DISABLED,
		ALERT_MAIN_START_LENS_FAILED,
		ALERT_CHATSOURCE_RENAME_CONTENT,
		ALERT_CHATSOURCE_NO_NAME,
		ALERT_CHATSOURCE_RENAME_EXIST,
		ALERT_CONTACT_CHECK_NETWORK_ERROR,
		ALERT_CONTACT_EMAIL_FORMAT_ERROR,
		ALERT_CONTACT_FILE_FORMAT_ERROR,
		ALERT_CONTACT_FILE_MAX_COUNT,
		ALERT_SOURCE_REMOVE_TEMPLATE,
		ALERT_LIVEINFO_TITLE_OVER_LENGTH,
		ALERT_LIVEINFO_YOUTUBE_DESCRIPTION_LENGTH,
		ALERT_PAY_TERMS_RETRYLABEL,

		//
		ALERT_BAND_DESCRIPTION_MAX_LIMIT = 62500,
		ALERT_SOURCE_GUIDE_ALL_SAME,
		ALERT_SOURCE_GUIDE_PARTIAL_DUPLICATE,
		ALERT_SESSION_EXPIRED,
		ALERT_LOGOUT_CONFIRM,
		ALERT_NCB2B_SERVICE_DISABLE,
		ALERT_ACCOUNT_DELETE_CONFIRM,
		ALERT_ACCOUNT_ANDROID_SUBSCRIPTION_ACTIVE,
		ALERT_ACCOUNT_IOS_SUBSCRIPTION_ACTIVE,
		ALERT_ACCOUNT_CANCEL_SUBSCRIPTION_FIRST,
		ALERT_COMMON_TEMPORARY_ERROR,
		ALERT_RESET_UI_WARNING,
		ALERT_UPDATE_DOWNLOAD_FAILED,
		ALERT_LOGIN_B2B_ACCESS_DENIED,
		ALERT_NCB2B_SERVICE_NOT_FOUND,
		ALERT_RESET_PASSWORD_LINK_SENT,
		ALERT_YOUTUBE_HOST_BROWSER_ERROR,

		// LENS & filter
		ALERT_LENS_VB_NEED_UPGRADE = 64500,
		ALERT_LENS_VB_ACTIVE_DEVICE = 64501,
		ALERT_LENS_VB_NO_CAPTURE = 64502,
		ALERT_LENS_VB_TO_ORIGIN_CONFIRM = 64503,
		ALERT_LENS_CHROMAKEY_CONFIRM = 64504,
		ALERT_FILTER_CONFIRM_REMOVE = 64505,
		ALERT_FILTER_CONFIRM_RESET = 64506,
		ALERT_FILTER_NO_NAME_ENTER = 64507,
		ALERT_FILTER_NO_NAME_ENTER_NOTICE = 64508,
		ALERT_FILTER_NAME_EXIST = 64509,
		ALERT_FILTER_NAME_EXIST_NOTICE = 64510,
		ALERT_VCAM_FAILED_COMMON = 64511,
		ALERT_VCAM_FAILED_WITH_ERROR = 64512,
		ALERT_LAUNCH_LENS = 64513,
		ALERT_LAUNCH_MOBILE = 64514,
		ALERT_MOBILE_SCAN_QR_TIPS = 64515,
		ALERT_OPEN_LENS_TIPS = 64516,
		ALERT_PLUGIN_LOAD_FAIL = 64517,
		ALERT_3RD_CRASH_PLUGIN_IGNORE = 64518,

		ALERT_MULTITRACK_AUDIO_CHANNEL_INCOMPATIBLE = 64000,
		ALERT_AUDIO_MIXER_UNASSIGNED_WARNING = 64001,

		//ReplayBuffer
		ALERT_SIMPLE_REPLAY_BUFFER_STARTFAIL = 65000,
		ALERT_ADVANCE_REPLAY_BUFFER_STARTFAIL = 65001,
		ALERT_ADVANCE_REPLAY_BUFFER_STARTFAIL_BY_OUTPUTERROR = 65002,
		//MultitrackVideo
		ALERT_MULTITRACKVIDEO_WARNING_MESSAGE = 65010,
		ALERT_MULTITRACKVIDEO_WARNING = 65011,
		ALERT_MULTITRACKVIDEO_ERROR = 65012,

		//General Alert - Device
		ALERT_ENUM_DEVICE_TIMEOUT = 65500,

		//STICKER
		ALERT_STICKER_CHANGE_STICKER_WARNING = 66501,

		//ReplayBuffer
		ALERT_SIMPLE_REPLAY_BUFFER_STARTFAIL_MAC = 67003,
		ALERT_ADVANCE_REPLAY_BUFFER_STARTFAIL_MAC = 67004,

		ALERT_START_REPLAY_FAILED = 67000,
		ALERT_No_Name_Entered = 67001,
		ALERT_Name_Exists = 67002
	};
	Q_ENUM(ErrCode)

	enum class SearchType { apiError = 0, prismCode, errorCode, customError };

	struct ExtraData {

		ExtraData() {}
		explicit ExtraData(const QString &urlEnValue) : urlEn(urlEnValue) {}
		explicit ExtraData(const char *urlEnValue) : ExtraData(urlEnValue ? QString::fromUtf8(urlEnValue) : QString{}) {}

		QString platformName{};

		//when not found any matched error, will show unknown error.
		bool isShowUnknownError{true};

		//append object, which will combine with json->platform->extra->path value
		/**
		 default add key value:
		 {
		 "prismCode": 10000...
		 "prismName": COMMON_NETWORK_ERROR...
		 "platformName": Youtube, Chzzk...
		 "$statusCode": 200, only in network alert
		 "logPlatformName": = platformName
		 }
		 */
		QMap<QString, QString> pathValueMap{};
		//this list will append to alert message. join with appendJoin key.
		QStringList appendList{};
		QString appendJoin{" "};

		//if alert msg have 1%, this will use when json not contain err.arg parameter.
		QStringList defaultArg{};

		//json->platform->phase will be search with this value
		QString errPhase = PLSErrPhaseChannel;

		//log from
		QString urlKr{};
		QString urlEn{};
		//{{xxx}} will be format, will be combine with extra->logAppend
		QStringList logAppend{};

		// PLSAlertView method properties value;
		QMap<QString, QVariant> propertiesMap = QMap<QString, QVariant>();

		bool printLog{true};
	};

	struct RetData {
		bool isMatched{false}; //is matched this code
		QDialogButtonBox::StandardButton clickedBtn{QDialogButtonBox::NoButton};
		bool isCheckBoxClick{false};
		ErrCode prismCode{PLSErrorHandler::ErrCode::INVALID};
		QString prismName{};                   //prism code value name
		QString alertMsg{};                    //alert msg
		QString alertMsgEnglish{};             //alert msg
		QString alertMsgKey{};                 //alert key
		QString alertStage;                    //alert stage
		AlertType alertType{AlertType::Error}; //contact us or normal
		ErrorType errorType{ErrorType::Other}; //error type
		QString prismCodePrefix{};             //prism code value name prefix

		QJsonObject matchedObj{};  //json obj found
		QString failedLogString{}; //extra->logAppend formatted
		bool isNotError{false};
		ExtraData extraData{};   //extra data, with temp data
		bool isExactMatch{true}; //Find the exact error instead of default or unknown.
	};
	struct NetworkData {
		int statusCode{0};
		QNetworkReply::NetworkError netError{QNetworkReply::NetworkError::NoError};
		QByteArray errData{};
	};

	static PLSErrorHandler *instance();
	QJsonObject getRootObj() const;
	bool getTranslateString(const QString &key, QString &transVal, bool isSearchEnglish = false) const;
	bool getEnglishStrByOtherLang(const QString &otherLang, QString &engString) const;
	//for unit test, can not send analog and uistep
	bool isPrintLog() const { return m_isPrintLog; };
	void setIsPrintLog(bool isPrintLog) { m_isPrintLog = isPrintLog; };
	QJsonObject loadJson();

	static bool getUItranslation(const char *text, const char **out);

	/**
	 platformName: json first key
	 customErrName: the last compare key, default->data->api->defaultKey path
	 errPhase: the second path, YouTube->channel or YouTube->login or YouTube->live
	 defaultArg: msgkey %1, get the value
	 */
	static RetData getAlertString(const NetworkData &netData, const QString &platformName, const QString &customErrName, const ExtraData &extraData = {});
	static RetData showAlert(const NetworkData &netData, const QString &platformName, const QString &customErrName, const ExtraData &extraData = {}, QWidget *showParent = nullptr);
	static RetData getAlertString(const pls::http::Reply &reply, const QString &platformName, const QString &customErrName, const ExtraData &extraData = {})
	{
		return getAlertString({reply.statusCode(), reply.error(), reply.data()}, platformName, customErrName, extraData);
	};
	static RetData showAlert(const pls::http::Reply &reply, const QString &platformName, const QString &customErrName, const ExtraData &extraData = {}, QWidget *showParent = nullptr)
	{
		return showAlert({reply.statusCode(), reply.error(), reply.data()}, platformName, customErrName, extraData, showParent);
	};

	/**
	 customErrName: compare key, default->api->defaultKey path
	 */
	static RetData getAlertStringByCustomErrName(const QString &customErrName, const QString &platformName, const ExtraData &extraData = {});
	static RetData showAlertByCustomErrName(const QString &customErrName, const QString &platformName, const ExtraData &extraData = {}, QWidget *showParent = nullptr);

	/**
	 Streaming/Record Core Error
	 errorCode: YouTube->data->api->errorCode
	 customErrName: compare key, default->data->api->defaultKey path
	 */
	static RetData getAlertStringByErrCode(const QString &errorCode, const QString &platformName, const QString &customErrName, const ExtraData &extraData = {});
	static RetData showAlertByErrCode(const QString &errorCode, const QString &platformName, const QString &customErrName, const ExtraData &extraData = {}, QWidget *showParent = nullptr);

	static RetData getAlertStringByPrismCode(ErrCode prismCode, const QString &platformName, const QString &customErrName, const ExtraData &extraData = {});
	static RetData showAlertByPrismCode(ErrCode prismCode, const QString &platformName, const QString &customErrName, const ExtraData &extraData = {}, QWidget *showParent = nullptr);

	static QDialogButtonBox::StandardButton directShowAlert(RetData &data, QWidget *showParent = nullptr);

	static PLSErrorHandler::AlertType getButtonAndMsgDatas(QMap<PLSAlertView::Button, QString> &actionMap, QMap<PLSAlertView::Button, pls_text_t> &buttonsMap, RetData &data);
	static QString getButtonOpenUrl(const QString &str, const QMap<QString, QString> &pathValueMap);
	static void printLog(const RetData &retData, bool forcePrint = true);

private:
	PLSErrorHandler();
	PLSErrorHandler(const PLSErrorHandler &other) = delete;
	PLSErrorHandler &operator=(const PLSErrorHandler &other) = delete;

	static PLSErrorHandler::RetData getDataWithInheritList(const QJsonObject &rootObj, const QString &platformName, const NetworkData &netData, const QString &customErrName, ExtraData &extraData,
							       SearchType searchType);

	static QJsonObject getErrObjByPrismCode(ErrCode prismCode, const QJsonArray &jsonArray, const QString &platformName, const QString &customErrName, const ExtraData &extraData);
	static void fillUnknownDataIfEmpty(RetData &retData, ErrCode prismCode, const QString &platformName, const QString &customErrName, ExtraData &extraData, SearchType searchType);
	static QJsonObject getErrObj(const QJsonArray &jsonArray, const QString &platformName, const QString &customErrName, const ExtraData &extraData);

	static bool isDefaultKeyMatch(const QJsonObject &apiData, const QString &customErrName);

	static QJsonObject getPathValue(const QJsonObject &obj, const QString &platformName, const QJsonObject &apiJson);
	static std::pair<QString, QString> getOriginalAlertString(const QJsonObject &errorObj, const QString &msgKeyPath, const QString &msgTextPath);
	static QString dealOriginalAlertString(const QString &originalStr, const QJsonObject &errorObj, const ExtraData &extraData, bool isEnglish);
	static QJsonArray getButtonsObj(const QJsonObject &errorObj);
	static AlertType isContactUsDialog(const QString &str);
	static bool dealAlertAction(const QString &str, const QMap<QString, QString> &pathMap);
	static void showAlertInMain(RetData &data, QWidget *showParent);

	static RetData fillRetDataWithMatchObj(const QJsonObject &matchedObj, const QString &platformName, ExtraData &extraData, SearchType searchType);
	static QStringList getInheritList(const QJsonObject &obj, const QString &platformName);
	static bool isValidErrPhase(const QString &jsonPhase, const QString &userPhase);
	static ExtraData generateNewOtherData(const ExtraData &extraData, const QString &platformName);
	static QString &transAndDealValStr(QString &dealStr, const QJsonObject &errorObj, const ExtraData &extraData, bool isEnglish);

	QJsonObject m_rootJson{};
	QMap<QString, QString> m_iniMap;
	QMap<QString, QString> m_enIniMap;
	bool m_isPrintLog{true};
	mutable std::shared_mutex m_mutex;
};

Q_DECLARE_METATYPE(PLSErrorHandler::RetData)
